
name: "gulp-blender"
version: "1.0.0-rc.4"

# Environmn
dest: "./dist/"

# Configure gulp server task
server:
  port: 1337
  server:
    baseDir: "./dev/"
  ui:
    port: 1338
  ghostMode:
    clicks: "true"
    forms: "true"
    scroll: "true"
  logLevel: "info"
  logFileChanges: true
  logConnections: true
  logPrefix: "-server-"
  open: false
  reloadDelay: 500
  notify: false
  middleware: []

# Configure templates gulp task
templates:
  subDir: "/"
  src:
    - "./src/views/**/*.jade"
    - "!./src/views/**/_*.jade"
  jade:
    pretty: false

# Configure scripts gulp task
scripts:
  subDir: "/js"
  src:
    - "./src/js/**/*.js"
    - "!./src/js/vendor/**/*.js"
  lint:
    config: "./.eslintrc.json"
    src:
      - "./src/js/**/*.js"
      - "!./src/js/vendor/**/*.js"

  # Vendor specific options
  vendor:
    subDir: "js/vendor"
    src:
      - "./src/js/vendor/**/*.js"

# Configure styles gulp task
styles:
  subDir: "/css"
  src: "./src/scss/*.scss"
  cressDir: "./src/scss/cress"
  foundationDir: "./src/scss/foundation"
  # https://github.com/postcss/autoprefixer#options
  autoprefixer:
    browsers:
      - "ie >= 10"
      - "> 1%"
      - "last 2 versions"
      - "Firefox ESR"
      - "Opera 12.1"
    cascade: false

# Configuration for bower gulp task
bower:
  scripts:
    filter: "**/*.js"
    dest: "./src/js/vendor/"
  images:
    filter: "**/*.{png,gif,jpg,jpeg}"
    dest: "./src/img/vendor/"
  styles:
    filter:
      - "**/*.scss"
      - "**/*.css"
    dest: "./src/scss/vendor/"

# Static sources that will be automatically copied
static:
  images:
    src: "./src/img/**/*.{png,gif,jpg,jpeg}"
    subDir: "img/"
  rootassets:
    src: "./src/root/**/*"
    subDir: "/"
  svg:
    src: "./src/img/**/*.svg"
    subDir: "img/"
  ico:
    src: "./src/img/**/*.ico"
    subDir: "img/"
  fonts:
    src: "./src/fonts/**"
    subDir: "fonts/"
  videos:
    src: "./src/videos/**"
    subDir: "videos/"

# Note: static sources are automatically watched
watch:
  styles:
    src: "./src/scss/**/*.scss"
    tasks:
      - "styles"
  scripts:
    src: "./src/js/**/*.js"
    tasks:
      - "scripts"
  templates:
    src:
      - "./src/views/**/*.jade"
      - "./src/img/**/*.svg"
    tasks:
      - "templates"
